config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  devise_for :users

  resources :users do
  	resources :profile_managers	

  	resources :theatres do 
  		resources :screens do
  			resources :sections
  		end
  	end

  	resources :movies do 
  		resources :castings
  	end
  	
  	resources :movieshows do 
  		resources :bookings
    end

    resources :bookings
    resources :casts

    get 'screen_select' , to: "movieshows#screen_select"
    get 'assign_cast' , to: "casts#assign_cast"
  	get 'allshow' , to: "theatres#allshow"
  	get 'showmovies' , to: "movies#showmovies"
  	get 'show_details' , to: "movieshows#show_details"
  end
  	get '/sort_movie_show' , to:'movieshows#sort_movie_show'
  

  

  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :movieshow
  belongs_to :user
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :user
  has_one_attached :cast_image, dependent: :destroy
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :casts, dependent: :destroy
  has_many :movieshows, dependent: :destroy
  has_one_attached :thumbnail, dependent: :destroy
  has_many_attached :cover_pics, dependent: :destroy
  has_one_attached :trailer, dependent: :destroy
  self.inheritance_column = :_type_disabled



  validates :release_date,:thumbnail, :cover_pics, :trailer, presence: true
  validate :must_have_valid_future_date

  validates :thumbnail, presence: :true

  

  private

  def must_have_valid_future_date
    if release_date.present?
        unless release_date.is_a?(Date)
            errors.add(:release_date, "must be a valid date")
        end

        if release_date < Date.today
            errors.add(:release_date, "can't be in the past")
        end
    end
  end


end

app/models/movieshow.rb
class Movieshow < ApplicationRecord
  belongs_to :movie
  belongs_to :theatre
  belongs_to :screen
  has_many :bookings, dependent: :destroy

  validates :show_date, presence: true
  validate :must_have_valid_future_date

  private

  def must_have_valid_future_date
    if show_date.present?
        unless show_date.is_a?(Date)
            errors.add(:show_date, "must be a valid date")
        end

        if show_date < Date.today
            errors.add(:show_date, "can't be in the past")
        end
    end
  end


end

app/models/profile_manager.rb
class ProfileManager < ApplicationRecord
  belongs_to :user
  has_one_attached :picture, dependent: :destroy
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :sections, dependent: :destroy
  has_many :movieshows, dependent: :destroy

  

end

app/models/section.rb
class Section < ApplicationRecord

  belongs_to :screen
  
  validates :section_name, presence: true
  validates :seats, numericality: true
  validates_uniqueness_of :section_name, scope: :screen_id
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  belongs_to :user
  has_many :screens, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile_manager, dependent: :destroy
  has_many :theatres, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :casts, dependent: :destroy
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController

  def index
    @casts = Cast.all
  end

  def new
    @cast = current_user.casts.new
  end

  def create
    @cast = current_user.casts.create(cast_params)
    if @cast.save
      redirect_to welcome_index_path(current_user)
    else
      render "new"
    end
  end


  def assign_cast
    @assign_cast = Movie.find(params[:format]) 
    @casts = current_user.casts
  end


  private
  
  def cast_params
    params.require(:cast).permit(:name, :cast_image)
  end
end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
	
	def new
		@theatre = Theatre.new
	end

	def create
		@theatre = current_user.theatres.create(theatre_params)
		if @theatre.save
			redirect_to user_allshow_path(current_user)
		else
			render "new"
		end
	end

	def allshow
		@theatres = Theatre.all
	end

	def show
		@theatre = Theatre.find(params[:id])
	end

	def edit
		@theatre = current_user.theatres.find(params[:id])
	end

	def update
		@theatre = current_user.theatres.find(params[:id])
		if @theatre.update(theatre_params)
			redirect_to user_theatre_path(current_user, @theatre)
		else
			render 'edit'
		end
	end

	def destroy
		@theatre = current_user.theatres.find(params[:id])
		if @theatre.destroy
			redirect_to user_allshow_path(current_user)
		else
			p "Only current_user can delete"
		end
	end

	private 

	def theatre_params
		params.require(:theatre).permit(:user_id, :name, :address, :contact, :facilities)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/movieshows_helper.rb
module MovieshowsHelper

	

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
	def screen_model
		@screen = Screen.find_by(:params[:screen_id])
	end
end

app/helpers/sections_helper.rb
module SectionsHelper

end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/theatres/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <%= form_for ([current_user, @theatre]) do |form| %>
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %><br>
        <%= form.label :address %>
        <%= form.text_area :address, class: "form-control" %><br>
        <%= form.label :contact %>
        <%= form.text_field :contact, class: "form-control" %><br>
        <%= form.label :facilities %>
        <%= form.text_field :facilities, class: "form-control" %><br>
        <%= form.submit class: "btn btn-success" %>
      <%end %>
      <%= link_to "Back", user_allshow_path()%>
    </div>
  </div>
</div>

app/views/theatres/allshow.html.erb
<br>
<%= link_to "Add Theatre", new_user_theatre_path(current_user), class: "btn btn-primary" %><br>
<% if @theatres.present? %>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
				<% current_user.theatres.each  do |theatre| %><br>
					<div class="card" style="width: 18rem;">
					  <div class="card-body">
					    <%= theatre.name %>
					    <%= theatre.address %>
					    <%= theatre.contact %>
					    <%= link_to "Show theatre" , user_theatre_path(current_user,theatre.id), class: "btn btn-warning" %>
					    <%= link_to "Remove", user_theatre_path(current_user,theatre.id), method: :delete %>
					  </div>
					</div>
				<%end%>
			</div>
		</div>
	</div>
<%end%><br>
<%= link_to "Back", welcome_index_path, class: "btn btn-secondary" %>



			

app/views/theatres/edit.html.erb
<%= render partial: "form", object: @theatre %>

app/views/theatres/new.html.erb
<%= render partial: "form", object: @theatre %>

app/views/theatres/show.html.erb
<div class="container">
  <div class="row"><br>
    <div class="col-sm-4"><br>
      <strong>Name - </strong>
      <%= @theatre.name %><br>
      <strong>Address - </strong>
      <%= @theatre.address %><br>
      <strong>Contact - </strong>
      <%= @theatre.contact %><br>
      <strong>Facilities - </strong>
      <%= @theatre.facilities %><br>
    </div>
  </div><br>
    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Update</button>

  <div class="row">
    <div class="col-sm-6">
      <h3>Screens</h3>
      <% @theatre.screens.each do |theatre_screen| %>
      <div class="card">
          <div class="card-header">
            <%= theatre_screen.name %>
            <%= link_to "Delete Screen",user_theatre_screen_path(current_user, @theatre, theatre_screen), method: :delete %>
          </div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <table class="table">
              <tr>
                <th>Name</th>
                <th>Seats</th>
                <th>Price</th>
                <th>Edit</th>
                <th>Delete</th>
              </tr>
              <% theatre_screen.sections.each do|section| %>
              <tr>
                <td>
                    <%= section.section_name %>     
                </td>
                <td>
                  <%= section.seats %>
                </td>
                <td><%= section.price %></td>
                <td><%= link_to "Edit", edit_user_theatre_screen_section_path(current_user,section.screen.theatre, section.screen, section), class: "link" %></td>
                <td><%= link_to "Delete", user_theatre_screen_section_path(current_user,section.screen.theatre, section.screen, section), method: :delete, class: "link" %></td>
              </tr>
              <%end%>
            </table>
            <br>
            <footer class="blockquote-footer"><%= link_to "Add Sections", new_user_theatre_screen_section_path(current_user,@theatre, theatre_screen.id), class: "btn btn-info"%>
            </footer>
          </blockquote>
        </div>
      </div>
      <%end%>
    </div>
  </div><br><br>
  <div class="row">
    <div class="col-sm-4">
      <%= link_to "Add Screen", new_user_theatre_screen_path(current_user,@theatre.id), class: "btn btn-primary" %>
      <%= link_to "Back", welcome_index_path, class: "btn btn-danger" %>
    </div>
  </div>
  </div>
</div>



  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <%= render partial:"theatres/form"%>
        </div>
      </div>
    </div>
  </div>