config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  devise_for :users

  resources :users do
  	resources :profile_managers	

  	resources :theatres do 
  		resources :screens do
  			resources :sections
  		end
  	end

  	resources :movies do 
  		resources :castings
  	end
  	
  	resources :movieshows do 
  		resources :bookings
    end

    resources :bookings
    resources :casts

    get 'screen_select' , to: "movieshows#screen_select"
    get 'assign_cast' , to: "casts#assign_cast"
  	get 'allshow' , to: "theatres#allshow"
  	get 'showmovies' , to: "movies#showmovies"
  	get 'show_details' , to: "movieshows#show_details"
  end
  	get '/sort_movie_show' , to:'movieshows#sort_movie_show'
  

  

  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :movieshow
  belongs_to :user
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :user
  has_one_attached :cast_image, dependent: :destroy
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :casts, dependent: :destroy
  has_many :movieshows, dependent: :destroy
  has_one_attached :thumbnail, dependent: :destroy
  has_many_attached :cover_pics, dependent: :destroy
  has_one_attached :trailer, dependent: :destroy
  self.inheritance_column = :_type_disabled



  validates :release_date,:thumbnail, :cover_pics, :trailer, presence: true
  validate :must_have_valid_future_date

  validates :thumbnail, presence: :true

  

  private

  def must_have_valid_future_date
    if release_date.present?
        unless release_date.is_a?(Date)
            errors.add(:release_date, "must be a valid date")
        end

        if release_date < Date.today
            errors.add(:release_date, "can't be in the past")
        end
    end
  end


end

app/models/movieshow.rb
class Movieshow < ApplicationRecord
  belongs_to :movie
  belongs_to :theatre
  belongs_to :screen
  has_many :bookings, dependent: :destroy

  validates :show_date, presence: true
  validate :must_have_valid_future_date

  private

  def must_have_valid_future_date
    if show_date.present?
        unless show_date.is_a?(Date)
            errors.add(:show_date, "must be a valid date")
        end

        if show_date < Date.today
            errors.add(:show_date, "can't be in the past")
        end
    end
  end


end

app/models/profile_manager.rb
class ProfileManager < ApplicationRecord
  belongs_to :user
  has_one_attached :picture, dependent: :destroy
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :sections, dependent: :destroy
  has_many :movieshows, dependent: :destroy

  

end

app/models/section.rb
class Section < ApplicationRecord

  belongs_to :screen
  
  validates :section_name, presence: true
  validates :seats, numericality: true
  validates_uniqueness_of :section_name, scope: :screen_id
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  belongs_to :user
  has_many :screens, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile_manager, dependent: :destroy
  has_many :theatres, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :casts, dependent: :destroy
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def showmovies
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
    @casts = current_user.casts
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to user_showmovies_path(current_user,@movie)
    else
      render "edit"
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    if @movie.destroy
      redirect_to showmovies_path
    end
  end


  def create
    @movie = current_user.movies.create(movie_params)
    if @movie.save 
      redirect_to user_showmovies_path(current_user,@movie)
    else
      render "new"
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  


  private
  
  def movie_params
    params.require(:movie).permit(:name, :type, :summary, :thumbnail, :trailer, :release_date, :duration, cover_pics: [], cast_ids: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/movieshows_helper.rb
module MovieshowsHelper

	

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
	def screen_model
		@screen = Screen.find_by(:params[:screen_id])
	end
end

app/helpers/sections_helper.rb
module SectionsHelper

end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/movies/_form.html.erb
<%= form_for ([current_user,@movie]) do |f| %>
  <% if @movie.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@movie.errors.count, "error") %> prohibited
            this movie from being saved:
          </h2>
          <ul>
            <% @movie.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :name, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :type, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :type, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :summary, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_area :summary, class: "form-control" %>
        </div>
      </div>


      <div class="form-group">-
        <%= f.label :thumbnail, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.file_field :thumbnail, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :releaseDate, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.date_field :release_date, class: "form-control" %>
        </div>
      </div>


      <div class="form-group">
        <%= f.label :Duration, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :duration, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Cover Pictures:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.file_field :cover_pics,multiple: true, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "Trailer:", class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.file_field :trailer, class: "form-control" %>
        </div>
      </div>

      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
      <%= link_to "Back",user_showmovies_path(current_user) , class: "btn btn-warning" %>
 <% end %>

app/views/movies/edit.html.erb
<%= render partial: "form", object: @movie %>

app/views/movies/new.html.erb
<%= render partial:"form", object: @movie %>

app/views/movies/show.html.erb
<br>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Back", user_showmovies_path(current_user), class: "btn btn-danger"%>
<div class="container"><br>
  <div class="row">
    <div class="col-sm-12">
      <%= video_tag(url_for(@movie.trailer),style: 'height:auto;width:100%;',:controls =>true) %>
    </div>
  </div><br>
  <div class="row">
    <div class="col-sm-4">
      <h2><%= @movie.name %></h2>
      <h4><%= @movie.type %></h4>
    </div>
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <%= link_to "Book Now", user_show_details_path(current_user,@movie), class: "btn btn-info" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <%= @movie.summary %>
    </div>
  </div><br>
  <div class="row"><h2>Casts</h2>
    <% @movie.casts.each do |rec|%>
      <div class= "col-sm-3">
        <%= image_tag(rec.cast_image,class:"rounded-circle", alt: 'Description', style: 'display: block; margin: auto; width: 40%;')%>
        <center><%= rec.name%></center>
      </div>
    <%end%>
  </div><br><br><br>
  <div class="row">
    <% @movie.cover_pics.each do |pic| %>
    <div class="col-sm-12">
        <%= image_tag(pic, class: "img-fluid", alt: "Responsive image") %>
      <%end%>
    </div>
  </div><br><br>
  <div class="row">
    <div class="col-sm-8"></div>
  </div>
</div>

app/views/movies/showmovies.html.erb
<br>
<br>&nbsp;&nbsp;&nbsp;<%= link_to "Add Movie", new_user_movie_path(current_user), class: "btn btn-primary" %>
<%= link_to "Back", welcome_index_path, class: "btn btn-warning" %>	


<%= text_field "Search", id: "search_movie" %>


<% if @movies.present? %>
<div class="container"><br>
	<div class="row">
		<% current_user.movies.each do |movie| %> 
		&nbsp;&nbsp;<div class="col-sm-3">
			<div class="card" style="width: 18rem;">
				<%= image_tag(movie.thumbnail) %>
			  <div class="card-body">
				  <h3><%= movie.name%></h3>
					<p class="card-text"><%= movie.type%>  Release Date <%= movie.release_date%></p>
					<p class="card-text"></p>
					<%= link_to "Description", user_movie_path(current_user,movie), class: "btn btn-info" %>
					<%= link_to "Reviews", "#", class: "btn btn-info" %>
				  </div>
				  <%= link_to "Remove", user_movie_path(current_user,movie), method: :delete, class: "btn btn-danger" %>
				</div>
			</div>
		<%end%>
	</div>
</div>
<%end%>




<%#=select_tag :actors, options_from_collection_for_select(Cast.all, :id, :name), multiple: true %>