config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root "welcome#index"
  devise_for :users

  resources :users do
  	resources :profile_managers	

  	resources :theatres do 
  		resources :screens do
  			resources :sections
  		end
  	end

  	resources :movies do 
  		resources :castings
  	end
  	
  	resources :movieshows do 
  		resources :bookings
    end

    resources :bookings
    resources :casts

    get 'screen_select' , to: "movieshows#screen_select"
    get 'assign_cast' , to: "casts#assign_cast"
  	get 'allshow' , to: "theatres#allshow"
  	get 'showmovies' , to: "movies#showmovies"
  	get 'show_details' , to: "movieshows#show_details"
  end
  	get '/sort_movie_show' , to:'movieshows#sort_movie_show'
  

  

  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :movieshow
  belongs_to :user
end

app/models/cast.rb
class Cast < ApplicationRecord
  belongs_to :user
  has_one_attached :cast_image, dependent: :destroy
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :casts, dependent: :destroy
  has_many :movieshows, dependent: :destroy
  has_one_attached :thumbnail, dependent: :destroy
  has_many_attached :cover_pics, dependent: :destroy
  has_one_attached :trailer, dependent: :destroy
  self.inheritance_column = :_type_disabled



  validates :release_date,:thumbnail, :cover_pics, :trailer, presence: true
  validate :must_have_valid_future_date

  validates :thumbnail, presence: :true

  

  private

  def must_have_valid_future_date
    if release_date.present?
        unless release_date.is_a?(Date)
            errors.add(:release_date, "must be a valid date")
        end

        if release_date < Date.today
            errors.add(:release_date, "can't be in the past")
        end
    end
  end


end

app/models/movieshow.rb
class Movieshow < ApplicationRecord
  belongs_to :movie
  belongs_to :theatre
  belongs_to :screen
  has_many :bookings, dependent: :destroy

  validates :show_date, presence: true
  validate :must_have_valid_future_date

  private

  def must_have_valid_future_date
    if show_date.present?
        unless show_date.is_a?(Date)
            errors.add(:show_date, "must be a valid date")
        end

        if show_date < Date.today
            errors.add(:show_date, "can't be in the past")
        end
    end
  end


end

app/models/profile_manager.rb
class ProfileManager < ApplicationRecord
  belongs_to :user
  has_one_attached :picture, dependent: :destroy
end

app/models/screen.rb
class Screen < ApplicationRecord
  belongs_to :theatre
  has_many :sections, dependent: :destroy
  has_many :movieshows, dependent: :destroy

  

end

app/models/section.rb
class Section < ApplicationRecord

  belongs_to :screen
  
  validates :section_name, presence: true
  validates :seats, numericality: true
  validates_uniqueness_of :section_name, scope: :screen_id
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  belongs_to :user
  has_many :screens, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile_manager, dependent: :destroy
  has_many :theatres, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :casts, dependent: :destroy
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @profile = current_user.profile_manager if signed_in?
    @bookings = current_user.bookings if signed_in?
    @movies = Movie.all
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/movieshows_helper.rb
module MovieshowsHelper

	

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/screens_helper.rb
module ScreensHelper
	def screen_model
		@screen = Screen.find_by(:params[:screen_id])
	end
end

app/helpers/sections_helper.rb
module SectionsHelper

end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_after_login.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Movie Booking</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <%= link_to "Theatres", user_allshow_path(current_user), class: "nav-link", :id => 'theatreshow' %>
      </li>
      <li class="nav-item active">
        <%= link_to "Movies", user_showmovies_path(current_user), class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "Shows", user_movieshows_path(current_user), class: "nav-link"%>
      </li>
      <li class="nav-item">
      	<%= link_to "Bookings", user_bookings_path(current_user), class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Casting" ,user_casts_path(current_user), class: "nav-link"%>

      </li>

    </ul>
    <ul class="navbar-nav">
      <li><%= link_to 'Logout', destroy_user_session_path, :class => "nav-link", method: :delete, data: {confirm:"Are you Sure"} %>
      </li>
    </ul>
    

app/views/welcome/_before_login.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Movie Booking</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav">
          <li>
            <%= link_to 'Sign In', new_user_session_path, :class => "nav-link"%>
          </li>
    </ul>
    

app/views/welcome/index.html.erb
<% if @movies.present? %>
<div class="container"><br>
	<div class="row" id="movies">
		<% current_user.movies.each do |movie| %> 
		&nbsp;&nbsp;<div class="col-sm-3">
			<div class="card" style="width: 20rem;">
				<%= image_tag(movie.thumbnail) %>
			  <div class="card-body">
				  <center><h3><%= movie.name%></h3></center>
					<p class="card-text"><%= movie.type%>  Release Date <%= movie.release_date%></p>
					<p class="card-text"></p>
					<%= link_to "Description", user_movie_path(current_user,movie), class: "btn btn-info" %>
					<%= link_to "Reviews", "#", class: "btn btn-info" %>
				  </div>
				</div>
			</div>
		<%end%>
	</div>
</div>
<%end%>

app/views/welcome/index.js.erb
$(".a-unique-class").html('<%= j render "screens/_form" %>')

app/views/welcome/new.html.erb
<%= render partial: 'form', object: @profile %>